import eorpy
e = eorpy.eor()
e.set2sza()
e.setSys(z=3.)
e.setSys(restFreq=115.)
e.setSys(BW=2.)
e.setSys(rotate=False)
e.setTrack(HAmin=-4.)
e.setTrack(HAmax=4.)
e.setTrack(tobs=400.)
e.setPlot(plotModel=True)
#e.setPlot(plotBins=True)
e.setPlot(plotSteps=True)
e.setSys(dlogk=0.2)
e.arraySensitivity()
